### ISSUE TITLE
自建服务器时添加某星账号时报错

### ISSUE THREAD

**Issue by ZeroNeiko** [kuizuo/chaoxing-sign#32]
添加账号时报Cookie has domain set to a public suffix错误
无论是使用`pnpm run preview`还是`npm run start:pm2`都会出现此错误
```
[nuxt] [request error] [unhandled] [500] Cookie has domain set to a public suffix
  at Request._beforeError (./server/node_modules/got/dist/source/core/index.js:310:21)  
  at Request._onResponseBase (./server/node_modules/got/dist/source/core/index.js:625:22)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Request._onResponse (./server/node_modules/got/dist/source/core/index.js:765:13)  
  at CookieJar.setCookie (./server/node_modules/tough-cookie/lib/cookie.js:1186:15)  
  at ./server/node_modules/universalify/index.js:13:12  
  at new Promise (<anonymous>)  
  at CookieJar.setCookie (./server/node_modules/universalify/index.js:7:14)  
  at ./server/node_modules/got/dist/source/core/index.js:612:82  
  at Array.map (<anonymous>)  
  at Request._onResponseBase (./server/node_modules/got/dist/source/core/index.js:612:39)  
  at Request._onResponse (./server/node_modules/got/dist/source/core/index.js:765:24)  
  at ClientRequest.<anonymous> (./server/node_modules/got/dist/source/core/index.js:783:23)  
  at Object.onceWrapper (node:events:632:26)
```
测试请求地址为`ip+端口`和`域名+端口`，依旧还是会报以上错误
该条请求报500 Internal Server Error错误
求大佬们解惑

**Comment by kuizuo** [comment]
本地测试有无问题？

超星对某些服务器（例如阿里云）是有 ip 检测的，这些服务器是无法访问超星服务器的，你可以通过 curl https://passport2.chaoxing.com/ 来测试，返回空则正常，如下图结果则服务器 ip 被拉黑了。

![image](https://github.com/kuizuo/chaoxing-sign/assets/61005888/e132682f-100f-4c41-a8b5-0f5fc5a51540)

**Comment by ZeroNeiko** [comment]
> 本地测试有无问题？
> 
> 超星对某些服务器（例如阿里云）是有 ip 检测的，这些服务器是无法访问超星服务器的，你可以通过 curl https://passport2.chaoxing.com/ 来测试，返回空则正常，如下图结果则服务器 ip 被拉黑了。
> 
> ![image](https://private-user-images.githubusercontent.com/61005888/288038160-e132682f-100f-4c41-a8b5-0f5fc5a51540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODA1ODYsIm5iZiI6MTcwMTc4MDI4NiwicGF0aCI6Ii82MTAwNTg4OC8yODgwMzgxNjAtZTEzMjY4MmYtMTAwZi00YzQxLWE4YjUtMGY1ZmM1YTUxNTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDEyNDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3N2NkNGJlZjlhNTcwYjJhYzA3M2VmZDc4MzU2MDUwYzY1YzdmMzczNzBjYTkwYzNmZDg4M2RkMzA2NzQzMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gOv_X7lo2UPgHz4IkBN4GQfHue8hdzD6b0zxWK7q3fc)


大佬您好，部署的服务器是在学校寝室的实体机，校园网的IP是能够正常登录使用超星
curl https://passport2.chaoxing.com/命令测试也是正常的返回空值
![屏幕截图 2023-12-05 204335](https://github.com/kuizuo/chaoxing-sign/assets/74578447/cb4fd9d5-e02e-47bf-a275-8fd7f6e218d9)
应该不存在ip被拉黑的情况，感谢大佬的回复！

**Comment by soundofautumn** [comment]
自建服务器临时解决方案：
注释掉server/protocol/cx/index.ts的132-135行后，重新编译并部署。
怀疑是学校自建的超星平台导致重定向到学校域名导致的问题
不过会导致头像等功能不显示，其余功能自测可用

async parseUserInfo(data: CX.LoginResult) {
    this.user = {
      ...this.user,
      ...data,
      uid: String(data.uid),
    } as unknown as CX.User
    // const { body: html } = await this.http.get(`http://i.chaoxing.com/base?t=${timestamp()}`, { responseType: 'text' })
    // const $ = cheerio.load(html)
    // this.user.avatar = `${$('.head-img').attr('src')! + this.user.uid}_80`
    // this.user.siteName = $('#siteName').attr('title')
  }
